export enum PubsubTopic {
  API_ERROR = "API_HTTP_STATUS_NOT_SUCCESS",
  FORCE_LOGIN = "FORCE_LOGIN",
  NOTIFICATION = "NOTIFICATION",
  OPEN_CONFIRMATION_MODAL = "OPEN_CONFIRMATION_MODAL",
}

export enum NotificationLevel {
  INFO = "INFO",
  SUCCESS = "SUCCESS",
  WARNING = "WARNING",
  ERROR = "ERROR",
}
