import {
  IconApartment,
  IconBell,
  IconCalendar,
  IconCustomize,
  IconFile,
  IconHome,
  IconKanban,
  IconMoneyExchangeStroked,
  IconTaskMoneyStroked,
  IconTestScoreStroked,
  IconTickCircle,
  IconUser,
  IconUserAdd,
  IconUserGroup,
  IconGift,
} from '@douyinfe/semi-icons';
import { UserRole } from './auth.constants';

export interface IMenuOption {
  text?: string;
  itemKey?: string;
  icon?: any;
  items?: any[];
  url?: string;
  allowedRoles?: UserRole[];
}

export const menuOptions: IMenuOption[] = [
  {
    itemKey: 'dashboard',
    text: 'Trang chủ',
    url: '/dashboard',
    icon: <IconHome size="large" />,
  },
  {
    itemKey: 'companies',
    text: 'Quản lý doanh nghiệp',
    icon: <IconApartment size="large" />,
    url: '/companies',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.HR_ADMIN,
      UserRole.ACCOUNTANT,
      UserRole.SALE,
      UserRole.RECONCILER,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
    ],
  },
  {
    itemKey: 'campaigns',
    text: 'Quản lý chiến dịch',
    icon: <IconCalendar size="large" />,
    url: '/campaigns',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.SALE,
      UserRole.RECONCILER,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
    ],
  },
  {
    itemKey: 'notifications',
    text: 'Quản lý thông báo',
    icon: <IconBell size="large" />,
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.CONTROLLER,
      UserRole.CUSTOMER_SERVICE,
      UserRole.SALE,
    ],
    items: [
      {
        itemKey: 'notifications-templates',
        text: 'Thông báo tự động',
        url: '/notifications/templates',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.CONTROLLER,
          UserRole.CUSTOMER_SERVICE,
        ],
      },
      {
        itemKey: 'notifications-establish',
        text: 'Thông báo thiết lập',
        url: '/notifications/establish',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
        ],
      },
    ],
  },
  {
    itemKey: 'ticket-management',
    text: 'Quản lý yêu cầu',
    icon: <IconTickCircle size="large" />,
    url: '/ticket-management',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.SALE,
      UserRole.CUSTOMER_SERVICE,
      // UserRole.HR_ADMIN,
    ],
  },
  {
    text: 'Quản lý đối soát',
    itemKey: 'reconciliation',
    icon: <IconFile size="large" />,
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.ACCOUNTANT,
      UserRole.HR_ADMIN,
      UserRole.CONTROLLER,
      UserRole.RECONCILER,
    ],
    items: [
      {
        itemKey: 'reconciliation-bank',
        text: 'Đối soát ngân hàng',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.ACCOUNTANT,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
        ],
        items: [
          {
            itemKey: 'reconciliation-vpbank',
            text: 'Đối soát BEAM-VPBANK',
            url: '/reconciliation/vpbank',
            allowedRoles: [
              UserRole.BEAM_ADMIN,
              UserRole.SUPER_ADMIN,
              UserRole.ACCOUNTANT,
              UserRole.CONTROLLER,
              UserRole.RECONCILER,
            ],
          },
          // {
          //   itemKey: 'reconciliation-pvcbank',
          //   text: 'Đối soát BEAM-PVCBANK',
          //   url: '/reconciliation/pvcbank',
          //   allowedRoles: [
          //     UserRole.BEAM_ADMIN,
          //     UserRole.SUPER_ADMIN,
          //     UserRole.ACCOUNTANT,
          //     UserRole.CONTROLLER,
          //     UserRole.RECONCILER,
          //   ],
          // },
          {
            itemKey: 'reconciliation-vietcombank',
            text: 'Đối soát BEAM-VCB',
            url: '/reconciliation/vietcombank',
            allowedRoles: [
              UserRole.BEAM_ADMIN,
              UserRole.SUPER_ADMIN,
              UserRole.ACCOUNTANT,
              UserRole.CONTROLLER,
              UserRole.RECONCILER,
            ],
          },
        ],
      },

      {
        itemKey: 'reconciliation-concern',
        text: 'Đối soát với doanh nghiệp',
        url: '/reconciliation/concern',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.ACCOUNTANT,
          UserRole.HR_ADMIN,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
        ],
      },
    ],
  },
  {
    itemKey: 'configurations-admin',
    text: 'Cấu hình',
    icon: <IconCustomize size="large" />,
    url: '/configurations/basic',
    allowedRoles: [UserRole.BEAM_ADMIN, UserRole.SUPER_ADMIN],
  },

  {
    itemKey: 'configurations-sale',
    text: 'Cấu hình',
    icon: <IconCustomize size="large" />,
    url: '/configurations/company-type',
    allowedRoles: [
      UserRole.SALE,
      UserRole.CUSTOMER_SERVICE,
      UserRole.RECONCILER,
      UserRole.CONTROLLER,
    ],
  },
  {
    itemKey: 'configurations-accountant',
    text: 'Cấu hình',
    icon: <IconCustomize size="large" />,
    url: '/configurations/campaign-type',
    allowedRoles: [UserRole.ACCOUNTANT],
  },

  {
    text: 'Chính sách phí',
    itemKey: 'fee-policies',
    icon: <IconTaskMoneyStroked size="large" />,
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.ACCOUNTANT,
      UserRole.SALE,
      UserRole.RECONCILER,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
    ],
    items: [
      {
        itemKey: 'fee-policies-templates',
        text: 'Biểu mẫu chính sách phí',
        url: '/fee-policies/templates',
      },
      {
        itemKey: 'fee-policies-assign',
        text: 'Gán chính sách phí',
        url: '/fee-policies/assign',
      },
    ],
  },
  {
    text: 'Công nợ - dòng tiền',
    icon: <IconMoneyExchangeStroked />,
    itemKey: 'expenditure',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.ACCOUNTANT,
      UserRole.RECONCILER,
      UserRole.CONTROLLER,
    ],
    items: [
      {
        itemKey: 'expenditure-debt-expenditure',
        text: 'Công nợ',
        url: '/expenditure/debt/expenditure',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.ACCOUNTANT,
          UserRole.RECONCILER,
          UserRole.CONTROLLER,
          UserRole.CUSTOMER_SERVICE,
        ],
      },
      {
        itemKey: 'expenditure-finance-overview',
        text: 'Dòng tiền',
        url: '/expenditure/finance/overview',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.ACCOUNTANT,
          UserRole.RECONCILER,
          UserRole.CONTROLLER,
        ],
      },
      // {
      //   itemKey: 'expenditure-balance-outstanding-balance',
      //   text: 'Quản lý dư nợ',
      //   url: '/expenditure/balance/outstanding-balance',
      //   allowedRoles: [
      //     UserRole.BEAM_ADMIN,
      //     UserRole.SUPER_ADMIN,
      //     UserRole.ACCOUNTANT,
      //     UserRole.CUSTOMER_SERVICE,
      //     UserRole.CONTROLLER,
      //     UserRole.SALE,
      //   ],
      // },
    ],
  },
  {
    text: 'Công nợ',
    icon: <IconMoneyExchangeStroked />,
    itemKey: 'expenditure-debt-expenditure-hr',
    url: '/expenditure/debt/expenditure',
    allowedRoles: [UserRole.HR_ADMIN, UserRole.CUSTOMER_SERVICE],
  },
  {
    text: 'Báo cáo',
    itemKey: 'report',
    icon: <IconTestScoreStroked size="large" />,
    items: [
      {
        itemKey: 'report-transaction',
        text: 'Báo cáo theo giao dịch',
        url: '/report/transaction',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.HR_ADMIN,
          UserRole.ACCOUNTANT,
          UserRole.SALE,
          UserRole.RECONCILER,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
        ],
      },
      {
        itemKey: 'report-operations',
        text: 'Báo cáo vận hành',
        url: '/report/operations',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
        ],
      },
    ],
  },
  {
    text: 'Quản lý tài khoản',
    itemKey: 'end-user',
    icon: <IconUser size="large" />,
    url: '/end-user',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.SALE,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
    ],
    items: [
      {
        itemKey: 'end-user-beam-admin',
        text: 'Quản lý tài khoản Admin',
        url: '/end-user/beam-admin',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CONTROLLER,
        ],
      },
      {
        itemKey: 'end-user-hr-admin',
        text: 'Quản lý tài khoản HR Admin',
        url: '/end-user/hr-admin',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
        ],
      },
      {
        itemKey: 'end-user-user',
        text: 'Quản lý tài khoản người dùng',
        url: '/end-user/user',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
        ],
      },
    ],
  },
  {
    text: 'Quản lý giới thiệu bạn bè',
    itemKey: 'invite-friends',
    icon: <IconUserAdd size="large" />,
    url: '/invite-friends',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.SALE,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
      UserRole.RECONCILER,
      UserRole.ACCOUNTANT,
    ],
    items: [
      // {
      //   itemKey: 'friends-invitation-list',
      //   text: 'Danh sách chương trình giới thiệu bạn bè',
      //   url: '/invite-friends/referral-program/listProgram',
      //   allowedRoles: [
      //     UserRole.BEAM_ADMIN,
      //     UserRole.SUPER_ADMIN,
      //     UserRole.SALE,
      //     UserRole.CUSTOMER_SERVICE,
      //     UserRole.CONTROLLER,
      //     UserRole.RECONCILER,
      //     UserRole.ACCOUNTANT,
      //   ],
      // },
      {
        itemKey: 'invite-friends-invitation-list',
        text: 'Danh sách giới thiệu',
        url: '/invite-friends/invitation-list/referrer',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
          UserRole.ACCOUNTANT,
        ],
      },
      {
        itemKey: 'invite-friends-rank',
        text: 'Theo dõi xếp hạng',
        url: '/invite-friends/rank',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
        ],
      },
      {
        itemKey: 'invite-friends-bonus',
        text: 'Quản lý chi thưởng',
        url: '/invite-friends/bonus/bonus-month',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
          UserRole.ACCOUNTANT,
        ],
      },
      {
        itemKey: 'invite-friends-budget',
        text: 'Quản lý ngân sách',
        url: '/invite-friends/budget',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.ACCOUNTANT,
        ],
      },
    ],
  },
  {
    text: 'Chiếc hộp thần kỳ',
    itemKey: 'lucky-box',
    icon: <IconGift size="large" />,
    url: '/lucky-box',
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.SALE,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
      UserRole.RECONCILER,
      UserRole.ACCOUNTANT,
    ],
    items: [
      {
        itemKey: 'lucky-box-participate',
        text: 'Danh sách tham gia',
        url: '/lucky-box/participate/overview',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
          UserRole.ACCOUNTANT,
        ],
      },
      {
        itemKey: 'lucky-box-reward',
        text: 'Danh sách nhận thưởng',
        url: '/lucky-box/reward/overview',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.ACCOUNTANT,
        ],
      },
      {
        itemKey: 'lucky-box-bonus',
        text: 'Danh sách chi thưởng',
        url: '/lucky-box/bonus/overview',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.RECONCILER,
          UserRole.ACCOUNTANT,
        ],
      },
      {
        itemKey: 'lucky-box-budget',
        text: 'Quản lý phần thưởng',
        url: '/lucky-box/budget',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
          UserRole.ACCOUNTANT,
        ],
      },
    ],
  },
  {
    text: 'Khách hàng',
    itemKey: 'customer',
    icon: <IconUserGroup size="large" />,
    allowedRoles: [
      UserRole.BEAM_ADMIN,
      UserRole.SUPER_ADMIN,
      UserRole.SALE,
      UserRole.CUSTOMER_SERVICE,
      UserRole.CONTROLLER,
    ],
    items: [
      {
        itemKey: 'customer-classification',
        text: 'Phân loại khách hàng',
        url: '/customer/classification',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
        ],
      },
      {
        itemKey: 'customer-statistics',
        text: 'Thống kê',
        url: '/customer/statistics',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
          UserRole.CUSTOMER_SERVICE,
          UserRole.CONTROLLER,
        ],
      },
    ],
  },
  {
    text: 'Quản lý tin tức',
    itemKey: 'news',
    icon: <IconKanban size="large" />,
    url: '/end-user',
    allowedRoles: [UserRole.BEAM_ADMIN, UserRole.SUPER_ADMIN, UserRole.SALE],
    items: [
      {
        itemKey: 'news-articles',
        text: 'Quản lý bài viết',
        url: '/news/articles',
        allowedRoles: [
          UserRole.BEAM_ADMIN,
          UserRole.SUPER_ADMIN,
          UserRole.SALE,
        ],
      },
    ],
  },
];
